// src/components/layouts/Navigation.vue
<script setup></script>

<template>
  <nav id="nav" class="section-nav">
    <ul id="nav-list" class="nav-list">
      <li>About</li>
      <li>Projects</li>
      <li>Experience</li>
      <li>Education</li>
      <li>Contact</li>
    </ul>
  </nav>
</template>

<style scoped>
.nav-list{
  display:flex;
  gap:1rem;
  justify-content:center;
  align-items: center;
  padding: 0;
  margin: 0;
}
</style>

// src/components/navigation.jsx
import React from "react";
import Link from "next/link";

const Navigation = () => {
  return (
    <div className="d-flex justify-content-end p-3 gap-1">
      <Link href="/" passHref>
        <span className="btn btn-sm  btn-custom">Home</span>
      </Link>
      <Link href="/project" passHref>
        <span className="btn btn-sm  btn-custom">Projects</span>
      </Link>
      <Link href="/experience" passHref>
        <span className="btn btn-sm  btn-custom">Experience</span>
      </Link>
      <Link href="/education" passHref>
        <span className="btn btn-sm  btn-custom">Education</span>
      </Link>
      <Link href="/contact" passHref>
        <span className="btn btn-sm btn-custom">Contact</span>
      </Link>
    </div>
  );
};

export default Navigation;
